### PR TITLE
fix: cli auth and error handling for flux tasks

### LINKED ISSUE #2578: Kapacitor cli does not handle authentication properly with flux tasks
Authentication is not handled properly as we do not parse the URL properly to parse out and forward the `Basic` authentication, if present.

Additionally we do not handle authentication errors well in the flux CLI as it they do not match the OpenAPI schema.

### PR DESCRIPTION
**Pull request by lesam**
Closes #2578 

Before:

➜  ./kapacitor -url http://steve:pas@localhost:9092 flux task list
undefined response type
➜  ./kapacitor -url http://steve:pass@localhost:9092 flux task list
undefined response type 

After:

➜  ./kapacitor -url http://steve:pas@localhost:9092 flux task list
Error: authorization failed
➜  ./kapacitor -url http://steve:pass@localhost:9092 flux task list
ID                      Name    Organization ID Organization    Status  Every   Cron
079625bc3aeb8000        poster                                  active  3s

###### Required for all non-trivial PRs
- [x] Rebased/mergable
- [ ] Tests pass
- [ ] CHANGELOG.md updated

### CODE REVIEW

**Review by docmerlin — APPROVED** [review]

File: services/httpd/handler.go [hunk 1]
```diff
@@ -555,13 +555,17 @@ func serveExpvar(w http.ResponseWriter, r *http.Request) {
 
 // HttpError writes an error to the client in a standard format.
 func HttpError(w http.ResponseWriter, err string, pretty bool, code int) {
+	w.Header().Set("Content-Type", "application/json")
```
Comment (docmerlin) [inline services/httpd/handler.go:558]: This is unnecessary, there is something that is already taking care of this, and it collides with that.
