### PR TITLE
test: fix flaky TestService_GetConfig #1367

### LINKED ISSUE #1367: Fix TestService_GetConfig
```
-- FAIL: TestService_GetConfig (0.03s)
	service_test.go:1070: expected to get an response on errC
```

### PR DESCRIPTION
**Pull request by docmerlin**
Fix flaky test
Closes #1367

### CODE REVIEW

File: services/config/service_test.go [hunk 1]
```diff
@@ -1033,67 +1033,76 @@ func TestService_GetConfig(t *testing.T) {
...
+				}
+				defer resp.Body.Close()
+				body, err := ioutil.ReadAll(resp.Body)
+				if err != nil {
+					t.Fatal(err)
+				}
+				if got, exp := resp.StatusCode, http.StatusNoContent; got != exp {
+					t.Fatalf("update failed: got: %d exp: %d\nBody:\n%s", got, exp, string(body))
+				}
+				timeOut := time.NewTimer(5 * time.Second)
```
Comment (davidby-influx) [inline services/config/service_test.go:1075]: I'm always leery of tests that depend on timers, because they operate differently in different environments, but I don't have any good way to avoid it here.

File: services/config/service_test.go [hunk 2]
```diff
@@ -1033,67 +1033,76 @@ func TestService_GetConfig(t *testing.T) {
...
-				t.Fatalf("update failed: got: %d exp: %d\nBody:\n%s", got, exp, string(body))
-			}
-			select {
-			case err := <-errC:
-				if err != nil {
-					t.Fatal(err)
-				}
-			default:
-				t.Fatal("expected to get an response on errC")
+			defer resp.Body.Close()
```
Comment (davidby-influx) [inline services/config/service_test.go:1092]: Can the resp.Body.Close() fail? Should you capture the error and fail the test if so?

**Review by davidby-influx — APPROVED** [review]
Non-blocking  comments. LGTM

File: services/config/service_test.go (hunk 1 above)
Comment (docmerlin) [reply services/config/service_test.go:1075]: I don't either :-( This is just to reduce the fake-fail by letting it happen out of order sometimes.

File: services/config/service_test.go (hunk 2 above)
Comment (docmerlin) [reply services/config/service_test.go:1092]: Technically it can, but if it fails the problem isn't in the system we are testing, but in the underlying subsystem.
