### PR TITLE
fix: avoid infinite hang when closing Kakfa writer

### LINKED ISSUE #2497: Closing a Kafka writer hangs
* Our Kafka writers run a metric-collecting goroutine in the background.
* The goroutine `range`s over a `time.Ticker`'s channel, and calls `Done()` on a `sync.WaitGroup` after the `range` completes.
* `Close()` on the writer calls `Stop()` on the ticker, then `Wait()` on the wait group
* Calling `Stop()` on a ticker doesn't actually close its channel, so:
   * The `range` over the channel never completes
   * `Done()` is never called on the wait group
   * `Wait()` on the wait group never completes

### PR DESCRIPTION
**Pull request by danxmoran**
Fixes #2497

### CODE REVIEW

File: services/kafka/service_test.go [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+	diag := diagnostic.NewService(diagnostic.NewConfig(), os.Stderr, os.Stdin)
+	require.NoError(t, diag.Open())
+	defer diag.Close()
+
+	// Write a message to generate a writer.
+	require.NoError(t, cluster.WriteMessage(diag.NewKafkaHandler(), "testTopic", []byte{1, 2, 3, 4}, []byte{1, 2, 3, 4}))
+
+	// Update the config in a way that requires shutting down all active writers.
+	c.UseSSL = true
+	require.NoError(t, cluster.Update(c))
```
Comment (danxmoran) [inline services/kafka/service_test.go:33]: Without the changes in `service.go`, this test never completes.

File: services/kafka/service.go [hunk 2]
```diff
@@ -71,6 +75,7 @@ func (w *writer) Open() {
 	statsMap.Set(statWriteMessageCount, writeMessages)
 
 	w.ticker = time.NewTicker(time.Second)
+	w.tickerDone = make(chan struct{}, 1)
```
Comment (docmerlin) [inline services/kafka/service.go:78]: this doesn't need to have a `1)` since its only ever used by closing.  It isn't that big a deal though.

**Review by docmerlin — APPROVED** [review]
